#!/usr/bin/env bash

SOURCE=/autograder/source
SUBMIT=/autograder/submission
export SUBMIT_FILE=$(ls -1q $SUBMIT)
NUMSUB=$(echo "$SUBMIT_FILE" | wc -l)


if [ "$NUMSUB" == 1 ]
then
    cp $SUBMIT/*.pdf $SOURCE
    cd $SOURCE
    Rscript grade_tutorial.R
else
    echo "Please submit a single PDF file."
fi 
